/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'ff0397a3-5a17-44a8-bc78-e8028bec8e4e';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_8': 'startScreen_mobileimage_8',
        'mobilecollapsibleset_10': 'startScreen_mobilecollapsibleset_10',
        'mobilecollapsblock_11': 'startScreen_mobilecollapsblock_11',
        'mobilecollapsblockheader_12': 'startScreen_mobilecollapsblockheader_12',
        'mobilecollapsblockcontent_13': 'startScreen_mobilecollapsblockcontent_13',
        'mobilecollapsblock_14': 'startScreen_mobilecollapsblock_14',
        'mobilecollapsblockheader_15': 'startScreen_mobilecollapsblockheader_15',
        'mobilecollapsblockcontent_16': 'startScreen_mobilecollapsblockcontent_16',
        'mobilecollapsblock_17': 'startScreen_mobilecollapsblock_17',
        'mobilecollapsblockheader_18': 'startScreen_mobilecollapsblockheader_18',
        'mobilecollapsblockcontent_19': 'startScreen_mobilecollapsblockcontent_19',
        'mobilegroupedbuttons_25': 'startScreen_mobilegroupedbuttons_25',
        'mobilebutton_26': 'startScreen_mobilebutton_26',
        'mobilebutton_27': 'startScreen_mobilebutton_27',
        'mobilebutton_28': 'startScreen_mobilebutton_28'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

        /* mobilecollapsblock_11 */

        $("#startScreen_mobilecollapsblock_11 .ui-collapsible-heading-toggle").attr("tabindex", "3");

        /* mobilecollapsblock_14 */

        $("#startScreen_mobilecollapsblock_14 .ui-collapsible-heading-toggle").attr("tabindex", "3");

        /* mobilecollapsblock_17 */

        $("#startScreen_mobilecollapsblock_17 .ui-collapsible-heading-toggle").attr("tabindex", "3");

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});